### ISSUE TITLE
Github Action for Exakat won't fail

### ISSUE THREAD

**Issue by Un1matr1x** [exakat/exakat-ga#2]
I just added the default implementation for the "Github Action for Exakat" and the log shows some findings, but the check still succeeded and didn't fail as you can see [here](https://github.com/Wayfapper/website/pull/63/checks?check_run_id=2382068684)

I guess it's because of this line:
`No exakat.sarif in /usr/src/exakat/projects/review/exakat.sarif`

@exakat 

https://github.com/Wayfapper/website/pull/63

**Comment by Un1matr1x** [comment]
since this doesn't create any actions / response ... I close this issue. 😞

**Comment by arcticlinux** [comment]
So I was trying the exakat/exakat-ga and ran across this exact problem.

The `entrypoint.sh` only returns an exit code of 1 if the environment variable `INPUT_EXIT_ON_ISSUES` is set.

So in order for the action to throw an error on output `export INPUT_EXIT_ON_ISSUES=true` would need to be at the top of `entrypoint.sh` or as an ENV in the Dockerfile.

You can run the action configured liked this:
```yaml
    - name: Exakat
      uses: docker://exakat/exakat-ga
      env:
        INPUT_EXIT_ON_ISSUES: true
```
